#!/bin/bash

echo "🚀 Starting Blue-Green Deployment..."

echo "🟦 Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo "🟩 Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo "🔁 Applying service..."
kubectl apply -f kubeservice.yaml

echo "📦 Current running pods:"
kubectl get pods -l app=messaging-app

echo "🧠 Checking GREEN pod logs..."
GREEN_POD=$(kubectl get pods -l version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD

echo "✅ Blue-Green deployment completed!"
